---
# handlers file for lighthouse-role
- name: Start Lighthouse service
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    enabled: false
    name: nginx.service
    state: restarted
